@url = http://localhost:5020/gateway

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzM0NzI1NDMsImV4cCI6MTU3MzQ4MzM0MywiaWF0IjoxNTczNDcyNTQzfQ.f5TTlRjdUMj--9Wc5z_twVwYWZDYy1H9FV1pzJtawQT7WoL9jKxCscWpPLlyKrS6p0-RKTksKSkNZQZe85hQaQ
  
### Create Business
POST {{url}}/api/businesses/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Test Business",
    "TradingName": "Test Trading Name",
    "WebAddress" : "http://wwww.google.co.ul",
    "HeadContactFirstName": "Joe",
    "HeadContactSecondName": "Bloggs",
    "HeadContactContactNumber": "07568512675",
    "HeadContactEmail": "joe.bloggs@outlook.com",
    "HeadOfficePostCode": "HU10 7RT",
    "HeadOfficeAddressLine1": " 56 Bond Street",
    "HeadOfficeAddressLine2": "Hull"
}

