@url = http://localhost:5020/gateway/api/

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzMwNjExNzYsImV4cCI6MTU3MzA3MTk3NiwiaWF0IjoxNTczMDYxMTc2fQ.dFkV19u8ildVhLMBntYe8LVDCQVXHs_xVWO3DqvwRWhmRP5o1HPJCXlLEp4A1gOrrxacCsSA5HM58kl6AS7j_A

@refreshToken = WSvpmPpLEsQEVusaDi2zDXV0Ey/c6MPKIxLw3Ny574s=

### Get Operations

GET {{url}}operations/2f85fbe8-e8c2-42d1-aab7-01ace68db08c


### Create Business
POST {{url}}/businesses/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Test Business",
    "TradingName": "Test Trading Name",
    "WebAddress" : "http://wwww.google.co.ul",
    "HeadContactFirstName": "Joe",
    "HeadContactSecondName": "Bloggs",
    "HeadContactContactNumber": "07568512675",
    "HeadContactEmail": "joe.bloggs@outlook.com",
    "HeadOfficeAddressLine1": " 56 Bond Street",
    "HeadOfficeAddressLine2": "Hull"
}

### Get Business Summaries

GET {{url}}/businesses