@url = http://localhost:5020/gateway/api/

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzQxNjM2NzksImV4cCI6MTU3NDE3NDQ3OSwiaWF0IjoxNTc0MTYzNjc5fQ.8DnPt1VXdmk8WWs3NVnPf9xKF2eSfULcgapbbe55Y9OkqCzZEPq1fwTICYBoDdUp3plIn3ZVRVboa3JbdKUZQw

@refreshToken = WSvpmPpLEsQEVusaDi2zDXV0Ey/c6MPKIxLw3Ny574s=

### Get Operations

GET {{url}}operations/2f85fbe8-e8c2-42d1-aab7-01ace68db08c


### Create Business
POST {{url}}businesses/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Test Business",
    "TradingName": "Test Trading Name",
    "WebAddress" : "http://wwww.google.co.ul",
    "HeadContactFirstName": "Joe",
    "HeadContactSecondName": "Bloggs",
    "HeadContactContactNumber": "07568512675",
    "HeadContactEmail": "joe.bloggs@outlook.com",
    "HeadOfficeAddressLine1": " 56 Bond Street",
    "HeadOfficeAddressLine2": "Hull",
    "HeadOfficePostCode": "Hu10 7rt"
}

### Get Business Summaries

GET {{url}}businesses/
Authorization: Bearer {{jwt}}


### Get Business

GET {{url}}businesses/a36d08ce-a2cb-4787-933b-1ddb8eeaafd3
Authorization: Bearer {{jwt}}



### Update Business Details

@businessiD = a36d08ce-a2cb-4787-933b-1ddb8eeaafd3

POST {{url}}businesses/update-details
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": "{{businessiD}}",
    "name": "John Ford",
    "tradingName": "Ford LTD",
    "webAddress": "http://amazon.co.uk"
}


### Update Business Contact
POST {{url}}businesses/update-contact
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "businessId": "{{businessiD}}",
    "firstName": "John",
    "secondName": "Goodman",
    "email": "john.goodman@outlook.com",
    "contactNumber": "07456987456"
}

### Update Business Office
POST {{url}}businesses/update-office
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "businessId": "{{businessiD}}",
    "addressLine1": "unit 100 argyle street",
    "addressLine2": "Hull",
    "postCode": "HU12 8TH"
}