@url = http://localhost:5020/gateway/api/

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzU0NzAxMjgsImV4cCI6MTU3NTQ4MDkyOCwiaWF0IjoxNTc1NDcwMTI4fQ.UanWC6fuBlUIVBs4ERToHb3wUCBottRxQe9q7o0zwg2bHjlSy2httcyQ32G8-uX2aRd9sjWPuLLWoj1QkIhyMg

@refreshToken = WSvpmPpLEsQEVusaDi2zDXV0Ey/c6MPKIxLw3Ny574s=

### Get Operations

GET {{url}}operations/c11b99c8-fc02-426b-8b91-e29bf8d5d96d


### Create Business
POST {{url}}businesses/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Test Business 233",
    "TradingName": "Test Trading Name",
    "WebAddress" : "http://wwww.google.co.ul",
    "HeadContactFirstName": "Joe",
    "HeadContactSecondName": "Bloggs",
    "HeadContactContactNumber": "07568512675",
    "HeadContactEmail": "joe.bloggs@outlook.com",
    "HeadOfficeAddressLine1": " 56 Bond Street",
    "HeadOfficeAddressLine2": "Hull",
    "HeadOfficePostCode": "Hu10 7rt"
}

### Get Business Summaries

GET {{url}}businesses/
Authorization: Bearer {{jwt}}


### Get Business

GET {{url}}businesses/f11014b5-fd21-4bde-90f5-726782ba6b16
Authorization: Bearer {{jwt}}



### Update Business Details

@businessiD = 3e779db5-3382-4993-83b4-eff7b6767719

POST {{url}}businesses/update-details
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": "{{businessiD}}",
    "name": "John Ford",
    "tradingName": "Ford LTD",
    "webAddress": "http://amazon.co.uk"
}


### Update Business Contact
POST {{url}}businesses/update-contact
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "businessId": "{{businessiD}}",
    "firstName": "John",
    "secondName": "Gooman",
    "email": "john.goodman@outlook.com",
    "contactNumber": "07456987456"
}

### Update Business Office
POST {{url}}businesses/update-office
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "businessId": "{{businessiD}}",
    "addressLine1": "unit 100 argyle street",
    "addressLine2": "Hull",
    "postCode": "HU12 8TH"
}



################################################## SITE ####################################################################



POST {{url}}sites/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "businessId": "{{businessiD}}",
    "Name": "Main Office",        
    "firstName": "Joe",
    "secondName": "Bloggs",
    "contactNumber": "07568512675",
    "email": "joe.bloggs@outlook.com",
    "addressLine1": " 56 Bond Street",
    "addressLine2": "Hull",
    "postCode": "Hu10 7rt"
}


@siteId = ac3fed5d-3277-409e-972c-e800e072ae35

### Get Site
GET {{url}}sites/get/{{siteId}}
Authorization: Bearer {{jwt}}


### Get Site Summaries
GET {{url}}sites/summaries/{{businessiD}}
Authorization: Bearer {{jwt}}

### Update Site Details
POST {{url}}sites/update
Content-Type: application/json
Authorization: Bearer {{jwt}}

{    
    "siteId": "{{siteId}}",
    "name": "Update Office",            
    "addressLine1": " (Update) 56 Bond Street",
    "addressLine2": "Hull (Update)",
    "postCode": "LS10 7rt"
}

### Update Site Contact
POST {{url}}sites/update-contact
Content-Type: application/json
Authorization: Bearer {{jwt}}

{    
    "siteId": "{{siteId}}",
    "firstName": "Fred",
    "secondName": "Brand",
    "contactNumber": "07568512675",
    "email": "joe.bloggs@outlook.com"
}


### Add Site Resource

POST {{url}}sites/create-site-resource
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "siteId": "{{siteId}}",
    "name": "iPhone 10",
    "identifier": "45678457896243798589725346rgtwhghjfksdhkjfg"
}

@resourceId = 42e564e8-1c20-4a8e-afc2-6f76611585c9

### Get Site Resources
GET {{url}}sites/resources/{{siteId}}
Authorization: Bearer {{jwt}}

### Remove Site Resource

POST {{url}}sites/remove-site-resource
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "resourceId": "{{resourceId}}"
}