@url = http://localhost:5010

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIxM2Y1MjQzZi1hZTRiLTRkNTEtYmQ5Yy0yMmI3MTU3M2VkZjEiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzE5MTA4ODQsImV4cCI6MTU3MTkyMTY4NCwiaWF0IjoxNTcxOTEwODg0fQ.STkMcdC-07WbKP9IShJl1fIj9tSYpoPXRDxzxaBYatsC-70McILscprYJ7N9J1HtbTdBc27jtywQwa5LPphv3Q


### sign in admin

POST {{url}}/api/admin/sign-in-system
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test123"
}

### create admin

POST {{url}}/api/admin/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "test57563@test.com",
}

### complete admin

POST {{url}}/api/admin/complete
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "test@test.com",
    "code": "2a2877a4-c085-40c0-8a44-e04147288808",
    "password": "Test123",
    "passwordMatch": "Test123"
}