@url = http://localhost:5010

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzMwNjExNzYsImV4cCI6MTU3MzA3MTk3NiwiaWF0IjoxNTczMDYxMTc2fQ.dFkV19u8ildVhLMBntYe8LVDCQVXHs_xVWO3DqvwRWhmRP5o1HPJCXlLEp4A1gOrrxacCsSA5HM58kl6AS7j_A

@refreshToken = WSvpmPpLEsQEVusaDi2zDXV0Ey/c6MPKIxLw3Ny574s=


### sign in admin

POST {{url}}/api/admin/sign-in-system
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test123"
}

### create admin

POST {{url}}/api/admin/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "test57563@test.com",
}

### complete admin

POST {{url}}/api/admin/complete
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "test@test.com",
    "code": "2a2877a4-c085-40c0-8a44-e04147288808",
    "password": "Test123",
    "passwordMatch": "Test123"
}

### revoke refresh token
POST {{url}}/api/tokens/revoke
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "token": "{{refreshToken}}",    
}

