@url = http://localhost:5020

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzM3MzcyNDMsImV4cCI6MTU3Mzc0ODA0MywiaWF0IjoxNTczNzM3MjQzfQ.yJBzpdc9qnMLsEm1mvpggQ3HcTU1lczXgN-9yPCSqUZlewZnIAYtuWfLWEqGhDlXLsA0eFA5J9KSYL7zfkITDw

### Hit Api Test Controller Pass
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "true",    
}

### Hit Api Test Controller Fail
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "false",    
}