@url = http://localhost:5020

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzM0NzYyNjAsImV4cCI6MTU3MzQ4NzA2MCwiaWF0IjoxNTczNDc2MjYwfQ.LgA8A9Xic7XmnSl-rKyRr78mDporJHHtDYej9qNwY-9jMwtZG_N9wEfKnCMbJ0MjrITEkOkt1tcCgtw4yXJjfQ

### Hit Api Test Controller Pass
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "true",    
}

### Hit Api Test Controller Fail
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "false",    
}