@url = http://localhost:5020

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzM4NTI2OTAsImV4cCI6MTU3Mzg2MzQ5MCwiaWF0IjoxNTczODUyNjkwfQ.IMcZdjoQpOf7KHlHJHEXJyhU8PmhgkLJ4HrKeR7WelG7yXnw9t1uKJKAn_ObMM9oNR8gPg5dimwL2nJjOUi08g

### Hit Api Test Controller Pass
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "true",    
}

### Hit Api Test Controller Fail
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "false",    
}