@url = http://localhost:5013/business/api

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzM4NTQzNTQsImV4cCI6MTU3Mzg2NTE1NCwiaWF0IjoxNTczODU0MzU0fQ.h6MxhZNcJAMBT6L43qaroFD6Tw9Wi13mkQeGF1CzELE_a3JohKo1k3CLdQrOVVdNe4AMjnwamttGrfg1szTXgA
  
### Create Business
POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Name": "Test Business",
    "TradingName": "Test Trading Name",
    "WebAddress" : "http://wwww.google.co.ul",
    "HeadContactFirstName": "Joe",
    "HeadContactSecondName": "Bloggs",
    "HeadContactContactNumber": "07568512675",
    "HeadContactEmail": "joe.bloggs@outlook.com",
    "HeadOfficeAddressLine1": " 56 Bond Street",
    "HeadOfficeAddressLine2": "Hull"
}

### Get Business Summaries

GET {{url}}

