@url = http://localhost:5010
@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImItYWRtaW5AdGVzdC5jb20iLCJuYW1laWQiOiJlNThmODdmMi0zZDMzLTRmZjQtYTA0NC05MTVmMjQ2ZGZhMzQiLCJyb2xlIjoiQnVzaW5lc3NBZG1pbiIsImJ1c2luZXNzSWQiOiI5ZWFmMDljOC03NDIyLTQxNDItYjliNS1jMTYyYzk4OGE4Y2UiLCJuYmYiOjE1ODIxMTQxNzAsImV4cCI6MTU4MjEyNDk3MCwiaWF0IjoxNTgyMTE0MTcwfQ.ZR7xbICjQvyKS2g0uBLhbVbOWxPX0jPCH9l0sODyQoQ6zF6ma5y4PQoIAvTM3ExK34m5Mn9cyd3EkijDxqXSkg

@refreshToken = WSvpmPpLEsQEVusaDi2zDXV0Ey/c6MPKIxLw3Ny574s=

### sign in portal (standard || admin)

POST {{url}}/api/users/sign-in
Content-Type: application/json

{
    "email": "b-standard@test.com",
    "password": "Test123"
}

### portal admin

POST {{url}}/api/users/sign-in
Content-Type: application/json

{
    "email": "b-admin@test.com",
    "password": "Test123"
}

### sign in admin

POST {{url}}/api/admin/sign-in-system
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Test123"
}

### create admin

POST {{url}}/api/admin/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "s-admin@test.com",
}

### complete admin

POST {{url}}/api/admin/complete
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "test@test.com",
    "code": "2a2877a4-c085-40c0-8a44-e04147288808",
    "password": "Test123",
    "passwordMatch": "Test123"
}

### revoke refresh token
POST {{url}}/api/tokens/revoke
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "token": "{{refreshToken}}",    
}


### Create Business Admin

@BusinessId = b19be6af-19ab-4c6d-a706-e84205c2d4d7

POST {{url}}/api/admin/create-business-admin
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "b-admin@test.com",
    "businessId": "{{BusinessId}}"
}

### Get Business Accounts

GET {{url}}/api/admin/get-for-business/d573565c-4c45-4270-b567-da478c6e614c
Authorization: Bearer {{jwt}}

### Remove Business Admin

POST {{url}}/api/admin/remove
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": "c90c827c-a742-4829-8435-c792f39351e1",
    "businessId": "{{BusinessId}}"
}

### Create Standard User
POST {{url}}/api/users/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "email": "b-standard1@test.com",
    "businessId": "{{BusinessId}}"
}


### Complete User

POST {{url}}/api/users/complete
Content-Type: application/json

{
    "email": "b-standard1@test.com",
    "code": "36aca8d9-d120-465e-960f-c101aceb8a2a",
    "password": "Test123",
    "passwordConfirmation": "Test123"
}

### Request Reset User Password


POST {{url}}/api/users/request-reset
Content-Type: application/json

{
    "email": "b-adminsafsf@test.com",
}

### Reset User Password


POST {{url}}/api/users/reset-password
Content-Type: application/json

{
    "code": "518dd46d-a3d9-49ab-8083-1efd23dfc8c2",
    "email": "b-admin3@test.com",
    "password": "Test145",
    "passwordConfirm": "Test12345"
}


### Remove Account
POST {{url}}/api/users/remove/55a1d569-e0e6-49c4-a300-460d9473aaa2
Authorization: Bearer {{jwt}}

### Get All User Accounts
GET {{url}}/api/users/accounts
Authorization: Bearer {{jwt}}
