@url = http://localhost:5020

@jwt = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1laWQiOiIwM2I0NTIxYi0wYmQ1LTQ1M2UtOGIwZC03NGUwYTVlMThkMDkiLCJyb2xlIjoiU3lzdGVtQWRtaW4iLCJuYmYiOjE1NzQxNjM2NzksImV4cCI6MTU3NDE3NDQ3OSwiaWF0IjoxNTc0MTYzNjc5fQ.8DnPt1VXdmk8WWs3NVnPf9xKF2eSfULcgapbbe55Y9OkqCzZEPq1fwTICYBoDdUp3plIn3ZVRVboa3JbdKUZQw

### Hit Api Test Controller Pass
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "true",    
}

### Hit Api Test Controller Fail
POST {{url}}/api/test/pass
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "isPass": "false",    
}

### Hit Api Test Controller Issue
POST {{url}}/api/test/issue
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "message": "Hello their",    
}