version: '3.7'

services:      
    services.identity:
        container_name: identity
        image: '${DOCKER_REGISTRY-}servicesidentity'
        ports:
            - '5010:80'         
        build:
            context: .
            dockerfile: microservices/Services.Identity/Dockerfile      
        networks: 
            - cruncher

    services.operations:
        container_name: operations
        image: '${DOCKER_REGISTRY-}servicesoperations'
        ports: 
            - '5012:80'      
        build:
            context: .
            dockerfile: microservices/Services.Operations/Dockerfile
        networks: 
            - cruncher

            
    services.push:
        container_name: push
        image: ${DOCKER_REGISTRY-}servicespush
        build:
            context: .
            dockerfile: microservices/Services.Push/Dockerfile
        ports: 
            - '5015:80'
        networks: 
            - cruncher

    services.logs:
        container_name: logs
        image: ${DOCKER_REGISTRY-}serviceslogs
        build:
            context: .
            dockerfile: microservices/Services.Logs/Dockerfile
        ports: 
            - '5016:80'
        networks: 
            - cruncher

networks:
  cruncher:      
    driver: bridge    
    name: credit-cruncher-network        

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local
  redis:
    driver: local







