export enum SetupEvents {
    LOGIN = "SETUP/LOGIN",
    LOGIN_SUCCESFUL = "SETUP/LOGIN_SUCCESFUL",
    LOGIN_REJECTED = "SETUP/LOGIN_REJECTED",
    LOGIN_FORM_UPDATED = "SETUP/LOGIN_FORM_UPDATED",
    FETCH_SITES = "SETUP/FETCH_SITES",
    FETCHED_SITES = "SETUP/FETCHED_SITES",
    REJECTED_SITES = "SETUP/REJECTED_SITES",
    SITE_SELECTION_CHANGED = "SETUP/SITE_SELECTION_CHANGED",
    SITE_SELECTION_CONFIRMED = "SETUP/SITE_SELECTION_CONFIRMED"
}