export enum StaffEvents {
    FETCH_STAFF_STATE = "STAFF/FETCH_STAFF_STATE",
    FETCHED_STAFF_STATE = "STAFF/FETCHED_STAFF_STATE",
    FAILED_FETCHING_STAFF_STATE = "STAFF/FAILED_FETCHING_STAFF_STATE"
}