export enum VisitorEvents {
    FETCH_VISITORS = "VISITORS/FETCH_VISITORS",
    FETCHED_VISITORS = "VISITORS/FETCHED_VISITORS",
    REJECTED_VISITORS = "VISITORS/REJECTED_VISITORS",
    VISITOR_SELECTED = "VISITORS/VISITOR_SELECTED",
    VISITOR_SELECTION_CONFIRMED = "VISITORS/VISITOR_SELECTION_CONFIRMED",
    VISITOR_SELECTION_CANCELLED = "VISITORS/VISITOR_SELECTION_CANCELLED"
}