export enum VisitorFormEvents {
    FETCH_SPEC = "VISITOR_FORM/FETCH_SPEC",
    FETCHED_SPEC = "VISITOR_FORM/FETCHED_SPEC",
    REJECTED_SPEC = "VISITOR_FORM/REJECTED_SPEC",
    UPDATED = "VISITOR_FORM/UPDATED",
    ERRORS = "VISITOR_FORM/ERRORS"
}
